Traceback (most recent call last):
  File "/home/dallepez/algobio1718/src/main.py", line 55, in <module>
    main()
  File "/home/dallepez/algobio1718/src/main.py", line 34, in main
    BDDE_obj = BDDE(G, patients, k, parameters)
  File "/home/dallepez/algobio1718/src/lib/core.py", line 26, in __init__
    self.pre(self)
  File "/home/dallepez/algobio1718/src/lib/bounds.py", line 210, in pre_bound_kantorovich
    if self.mins[index][g][1] > self.mins[0][u][0]:
IndexError: list index out of range

real	0m11.559s
user	0m10.992s
sys	0m0.220s
