Traceback (most recent call last):
  File "/home/dallepez/algobio1718/src/main.py", line 55, in <module>
    main()
  File "/home/dallepez/algobio1718/src/main.py", line 34, in main
    BDDE_obj = BDDE(G, patients, k, parameters)
  File "/home/dallepez/algobio1718/src/lib/core.py", line 26, in __init__
    self.pre(self)
  File "/home/dallepez/algobio1718/src/lib/bounds.py", line 129, in pre_bound_means
    best_vectors[v][1]=min_prod
IndexError: list assignment index out of range

real	0m11.133s
user	0m10.702s
sys	0m0.181s
